server:
  port: 80
#192.168.191.148
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.191.148:3306/springbootjlvpc?serverTimezone-GMT%2B8;useUnicode=true&characterEncoding=utf-8
    username: root
    password: kim
  main:
    banner-mode: off
  redis:
    host: 192.168.191.148
    port: 6379
    password: kim
    lettuce:
      pool:
        max-active: 8 # 最大连接
        max-idle: 8
        min-idle: 0
        max-wait: 100
    database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
    db-config:
      logic-delete-field: del
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:demo/mapper/xml/*.xml
  type-aliases-package: demo.domain
logging:
  level:
    root: info

